### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by fislysandi** [inversepolarity/ZenTube#5]
is this just like an unhook plugin for firefox? https://addons.mozilla.org/en-US/firefox/addon/youtube-recommended-videos/

i just wanna ask can this plugin can do everything that plugin does?

if it does i will switch to this plugin.

**Comment by surajsharma** [comment]
i've been asked this before, i believe it does everything everything unhook does but unhook has a few more features however i am not aware of a plugin that works across all browsers so you can have a consistent youtube experience if you use different browsers. secondly i believe zentube is slightly more memory efficient as compared to other similar plugins.
